// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/thuc201995/srv_convert_file/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	WordToPDFEndpoint    endpoint.Endpoint
	DownloadFileEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.SrvConvertFileService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		WordToPDFEndpoint: MakeWordToPDFEndpoint(s),
	}
	for _, m := range mdw["WordToPDF"] {
		eps.WordToPDFEndpoint = m(eps.WordToPDFEndpoint)
	}
	return eps
}
